### ISSUE TITLE
Swift 2

### ISSUE THREAD

**Issue by olepor** [sascha/DrawerController#23]
Does seem to be some slight issues when trying to move the project over to swift 2. Has anyone had any experience with this yet?

**Comment by maltebaumann** [comment]
Could you be more specific on these "slight issues"? There is an already converted version in the **swift-2.0** branch.

**Comment by olepor** [comment]
I have now moved to the swift-2.0 branch, but upon compiling the project I get 19 errors in the "DrawerController" file, all of which, seem to be related to:

- "Use of undeclared type 'RawOptionSetType'

Which is weird, as it seems to still be available in the swift-2.0 api documentation. :/

**Comment by foosfam** [comment]
Absolutely great work guys..... I was able to POC a sample app in one evening!....  If there's anything I can do to help out just let me know.  Thanks!  (I can't believe there's not more people following this)

**Comment by prefect42** [comment]
Correct me if I am wrong, but I am having problems in compiling the framework in the XCode 7 Beta 2. Problem on my side or needs update?

**Comment by sascha** [comment]
@prefect42: Just updated the swift-2.0 branch to use OptionSetType instead of RawOptionSetType. It works with Beta 2 now.

@foosfam: Thanks! Most of the credit should go to the folks who wrote MMDrawerController though :-) We wrote DrawerController when Swift was released last year and especially with Swift 2 it could probably need an overhaul (guard statements, better error handling, better use of optional binding etc.). Unfortunately I don't have time for that at the moment, so if you'd like to make it better, I'm more than happy to accept pull requests.

**Comment by foosfam** [comment]
Well thanks to the MMDrawerController gents as well!!

I may pull the trigger on this and use on our next app.  The architecture and design have been approved so I'm going to test it out more over the weekend.

If there's anything I find or add I will let you guys know.....  Matt
