### ISSUE TITLE
UITableViewDelegate's didSelectRowAt method is not working

### ISSUE THREAD

**Issue by Miramas** [sascha/DrawerController#89]
I have a child view controller with table view. I am trying to disable gesture recognizer with
`

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
        appDelegate.drawerController?.openDrawerGestureModeMask = .custom
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        
        appDelegate.drawerController?.openDrawerGestureModeMask = .bezelPanningCenterView
    }` 

but unsuccessful . Is there any workarounds?

**Comment by maltebaumann** [comment]
Hey Miramas, do you actually provide a custom open drawer gesture implementation? What happens if you set the mask to .none?
In theory, the DrawerController is listening for swiping gestures and your `didSelectRow` should always be called. Did you ensure your tableview's delegate is configured correctly? Do other delegate methods (e.g. `willDisplayCell` get called?

**Comment by Miramas** [comment]
my bad, I actually had another gesture recognizer to hide keyboard. the framework is all gool. 
Sorry
